import { Employee, PayrollSettings, LeaveRequest, ActivityLog } from './types';

export const initialSettings: PayrollSettings = {
  baseWorkingDays: 26,
  pfPercentage: 12,
  ptAmount: 200,
  tdsPercentage: 10,
  incentiveBracket90: 10000,
  incentiveBracket80: 7000,
  incentiveBracket70: 5000,
  incentiveBracketUnder70: 2000
};

export const initialEmployees: Employee[] = [
  {
    id: "OASIS-001",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    department: "Sales",
    designation: "Sales Manager",
    joiningDate: "2021-03-15",
    baseSalary: 150000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 1,
    lateDays: 3, // 1 half day deduction (every 3 lates)
    halfDays: 0,
    overtimeHours: 8,
    attendancePercentage: 92.3,
    performanceScore: 94,
    salesGenerated: 1250000,
    targetAchievement: 108,
    policiesSold: 18,
    customerSatisfaction: 4.8,
    managerRating: 5,
    feedback: "Exceptional performance this month. Exceeded sales targets and maintained excellent client relations.",
    orgHierarchy: { manager: "Sanjay Mehta", role: "Manager" },
    leaveBalance: { casual: 4, sick: 6, paid: 12, unpaid: 1 },
    bonus: 5000
  },
  {
    id: "OASIS-002",
    name: "Priya Patel",
    email: "priya.patel@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    department: "HR",
    designation: "Senior HR Executive",
    joiningDate: "2021-08-01",
    baseSalary: 75000,
    payrollStatus: "Paid",
    presentDays: 25,
    absentDays: 0,
    lateDays: 2,
    halfDays: 1,
    overtimeHours: 0,
    attendancePercentage: 96.2,
    performanceScore: 88,
    customerSatisfaction: 4.5,
    managerRating: 4,
    feedback: "Priya successfully managed the Q2 appraisal cycle and coordinates recruitment activities efficiently.",
    orgHierarchy: { manager: "Vikram Malhotra", role: "Senior Executive" },
    leaveBalance: { casual: 3, sick: 5, paid: 14, unpaid: 0 },
    bonus: 2000
  },
  {
    id: "OASIS-003",
    name: "Amit Sharma",
    email: "amit.sharma@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
    department: "IT",
    designation: "Lead IT Engineer",
    joiningDate: "2020-11-10",
    baseSalary: 160000,
    payrollStatus: "Paid",
    presentDays: 23,
    absentDays: 2,
    lateDays: 1,
    halfDays: 1,
    overtimeHours: 12,
    attendancePercentage: 88.5,
    performanceScore: 91,
    customerSatisfaction: 4.9,
    managerRating: 5,
    feedback: "Led the migration of server infrastructure with zero downtime. Exceptional support capabilities.",
    orgHierarchy: { manager: "Vikram Malhotra", role: "Team Lead" },
    leaveBalance: { casual: 2, sick: 4, paid: 10, unpaid: 2 },
    bonus: 8000
  },
  {
    id: "OASIS-004",
    name: "Sunita Rao",
    email: "sunita.rao@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150",
    department: "Operations",
    designation: "Operations Lead",
    joiningDate: "2019-05-20",
    baseSalary: 95000,
    payrollStatus: "Paid",
    presentDays: 26,
    absentDays: 0,
    lateDays: 0,
    halfDays: 0,
    overtimeHours: 4,
    attendancePercentage: 100,
    performanceScore: 85,
    customerSatisfaction: 4.2,
    managerRating: 4,
    feedback: "Maintained 100% attendance and optimized the internal document dispatch workflow.",
    orgHierarchy: { manager: "Rahul Dravid", role: "Operations Specialist" },
    leaveBalance: { casual: 6, sick: 8, paid: 18, unpaid: 0 },
    bonus: 1000
  },
  {
    id: "OASIS-005",
    name: "Vikram Malhotra",
    email: "vikram.malhotra@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
    department: "Finance",
    designation: "VP Finance",
    joiningDate: "2018-01-15",
    baseSalary: 220000,
    payrollStatus: "Paid",
    presentDays: 25,
    absentDays: 1,
    lateDays: 2,
    halfDays: 0,
    overtimeHours: 0,
    attendancePercentage: 96.2,
    performanceScore: 95,
    customerSatisfaction: 4.7,
    managerRating: 5,
    feedback: "Outstanding leadership in corporate tax compliance and cost-saving audits.",
    orgHierarchy: { manager: "Board of Directors", role: "VP" },
    leaveBalance: { casual: 5, sick: 7, paid: 20, unpaid: 0 },
    bonus: 12000
  },
  {
    id: "OASIS-006",
    name: "Sneha Reddy",
    email: "sneha.reddy@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    department: "Claims",
    designation: "Claims Executive",
    joiningDate: "2023-02-18",
    baseSalary: 55000,
    payrollStatus: "Paid",
    presentDays: 22,
    absentDays: 2,
    lateDays: 4, // 1 half day deduction (every 3)
    halfDays: 2,
    overtimeHours: 6,
    attendancePercentage: 84.6,
    performanceScore: 78,
    customerSatisfaction: 3.9,
    managerRating: 3,
    feedback: "Claims processing speed is satisfactory, but needs to improve attendance and punctuality.",
    orgHierarchy: { manager: "Deepika Padukone", role: "Executive" },
    leaveBalance: { casual: 2, sick: 3, paid: 8, unpaid: 3 },
    bonus: 0
  },
  {
    id: "OASIS-007",
    name: "Sanjay Mehta",
    email: "sanjay.mehta@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150",
    department: "Sales",
    designation: "Sales Director",
    joiningDate: "2017-06-10",
    baseSalary: 250000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 2,
    lateDays: 1,
    halfDays: 0,
    overtimeHours: 0,
    attendancePercentage: 92.3,
    performanceScore: 96,
    salesGenerated: 3500000,
    targetAchievement: 120,
    policiesSold: 42,
    customerSatisfaction: 4.9,
    managerRating: 5,
    feedback: "Driving massive growth in enterprise insurance policies. Masterful business developer.",
    orgHierarchy: { manager: "Board of Directors", role: "Director" },
    leaveBalance: { casual: 8, sick: 10, paid: 22, unpaid: 0 },
    bonus: 20000
  },
  {
    id: "OASIS-008",
    name: "Deepika Padukone",
    email: "deepika.padukone@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    department: "Claims",
    designation: "Claims Manager",
    joiningDate: "2020-04-12",
    baseSalary: 110000,
    payrollStatus: "Paid",
    presentDays: 25,
    absentDays: 0,
    lateDays: 3, // 1 half day
    halfDays: 1,
    overtimeHours: 2,
    attendancePercentage: 96.2,
    performanceScore: 89,
    customerSatisfaction: 4.6,
    managerRating: 4,
    feedback: "Efficiently managed claims queue. Reduced average claim resolution time by 15%.",
    orgHierarchy: { manager: "Vikram Malhotra", role: "Manager" },
    leaveBalance: { casual: 4, sick: 5, paid: 15, unpaid: 0 },
    bonus: 4000
  },
  {
    id: "OASIS-009",
    name: "Rohit Sharma",
    email: "rohit.sharma@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150",
    department: "Sales",
    designation: "Sales Associate",
    joiningDate: "2023-05-15",
    baseSalary: 45000,
    payrollStatus: "Paid",
    presentDays: 21,
    absentDays: 4,
    lateDays: 6, // 2 half days
    halfDays: 1,
    overtimeHours: 15,
    attendancePercentage: 80.8,
    performanceScore: 74,
    salesGenerated: 450000,
    targetAchievement: 85,
    policiesSold: 6,
    customerSatisfaction: 4.0,
    managerRating: 3,
    feedback: "Active in lead generation, but need to improve on close rates and check-in times.",
    orgHierarchy: { manager: "Rajesh Kumar", role: "Associate" },
    leaveBalance: { casual: 1, sick: 2, paid: 5, unpaid: 4 },
    bonus: 1500
  },
  {
    id: "OASIS-010",
    name: "Virat Kohli",
    email: "virat.kohli@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=150",
    department: "IT",
    designation: "IT Support Specialist",
    joiningDate: "2023-09-01",
    baseSalary: 60000,
    payrollStatus: "Paid",
    presentDays: 25,
    absentDays: 1,
    lateDays: 2,
    halfDays: 0,
    overtimeHours: 10,
    attendancePercentage: 96.2,
    performanceScore: 82,
    customerSatisfaction: 4.4,
    managerRating: 4,
    feedback: "Diligent in resolving daily hardware and software tickets for the operations floor.",
    orgHierarchy: { manager: "Amit Sharma", role: "Specialist" },
    leaveBalance: { casual: 3, sick: 4, paid: 7, unpaid: 1 },
    bonus: 2500
  },
  {
    id: "OASIS-011",
    name: "Rahul Dravid",
    email: "rahul.dravid@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=150",
    department: "Operations",
    designation: "Operations Manager",
    joiningDate: "2020-01-22",
    baseSalary: 140000,
    payrollStatus: "Paid",
    presentDays: 26,
    absentDays: 0,
    lateDays: 1,
    halfDays: 0,
    overtimeHours: 5,
    attendancePercentage: 100,
    performanceScore: 92,
    customerSatisfaction: 4.7,
    managerRating: 5,
    feedback: "Exceptional operational oversight. Smooth execution of daily service level targets.",
    orgHierarchy: { manager: "Vikram Malhotra", role: "Manager" },
    leaveBalance: { casual: 5, sick: 9, paid: 19, unpaid: 0 },
    bonus: 6000
  },
  {
    id: "OASIS-012",
    name: "Ananya Pandey",
    email: "ananya.pandey@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150",
    department: "HR",
    designation: "HR Coordinator",
    joiningDate: "2023-11-15",
    baseSalary: 40000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 2,
    lateDays: 3, // 1 half day
    halfDays: 0,
    overtimeHours: 0,
    attendancePercentage: 92.3,
    performanceScore: 79,
    customerSatisfaction: 4.1,
    managerRating: 3,
    feedback: "Supports employee onboarding processes well. Needs to manage records databases more carefully.",
    orgHierarchy: { manager: "Priya Patel", role: "Coordinator" },
    leaveBalance: { casual: 2, sick: 3, paid: 5, unpaid: 2 },
    bonus: 500
  },
  {
    id: "OASIS-013",
    name: "Lakshmi Prasad",
    email: "lakshmi.prasad@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=150",
    department: "Finance",
    designation: "Finance Associate",
    joiningDate: "2022-06-01",
    baseSalary: 65000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 1,
    lateDays: 4, // 1 half day
    halfDays: 1,
    overtimeHours: 3,
    attendancePercentage: 92.3,
    performanceScore: 84,
    customerSatisfaction: 4.3,
    managerRating: 4,
    feedback: "Consistently process vendor payments accurately and manages expense reconciliation.",
    orgHierarchy: { manager: "Neha Gupta", role: "Associate" },
    leaveBalance: { casual: 3, sick: 5, paid: 9, unpaid: 1 },
    bonus: 2000
  },
  {
    id: "OASIS-014",
    name: "Venkatesh Naidu",
    email: "venkatesh.naidu@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150",
    department: "Claims",
    designation: "Claims Analyst",
    joiningDate: "2022-09-10",
    baseSalary: 70000,
    payrollStatus: "Paid",
    presentDays: 23,
    absentDays: 2,
    lateDays: 5, // 1 half day
    halfDays: 1,
    overtimeHours: 8,
    attendancePercentage: 88.5,
    performanceScore: 81,
    customerSatisfaction: 4.2,
    managerRating: 4,
    feedback: "Strong analytical skill set, has identified multiple fraudulent claims reports this month.",
    orgHierarchy: { manager: "Deepika Padukone", role: "Analyst" },
    leaveBalance: { casual: 2, sick: 4, paid: 8, unpaid: 2 },
    bonus: 3000
  },
  {
    id: "OASIS-015",
    name: "Tanvi Shah",
    email: "tanvi.shah@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=150",
    department: "IT",
    designation: "Senior IT Engineer",
    joiningDate: "2021-07-22",
    baseSalary: 120000,
    payrollStatus: "Paid",
    presentDays: 25,
    absentDays: 0,
    lateDays: 2,
    halfDays: 1,
    overtimeHours: 6,
    attendancePercentage: 96.2,
    performanceScore: 90,
    customerSatisfaction: 4.8,
    managerRating: 5,
    feedback: "Handled security auditing successfully. Proactively updates database firewall parameters.",
    orgHierarchy: { manager: "Amit Sharma", role: "Senior Engineer" },
    leaveBalance: { casual: 4, sick: 5, paid: 13, unpaid: 0 },
    bonus: 5000
  },
  {
    id: "OASIS-016",
    name: "Rohan Joshi",
    email: "rohan.joshi@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1542103749-8ef59b94f47e?w=150",
    department: "Sales",
    designation: "Sales Associate",
    joiningDate: "2023-01-15",
    baseSalary: 50000,
    payrollStatus: "Paid",
    presentDays: 23,
    absentDays: 2,
    lateDays: 3, // 1 half day
    halfDays: 1,
    overtimeHours: 10,
    attendancePercentage: 88.5,
    performanceScore: 83,
    salesGenerated: 600000,
    targetAchievement: 95,
    policiesSold: 10,
    customerSatisfaction: 4.4,
    managerRating: 4,
    feedback: "Decent performance. Reached individual sales target and managed customer relations well.",
    orgHierarchy: { manager: "Rajesh Kumar", role: "Associate" },
    leaveBalance: { casual: 3, sick: 4, paid: 9, unpaid: 1 },
    bonus: 2000
  },
  {
    id: "OASIS-017",
    name: "Aditi Rao",
    email: "aditi.rao@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150",
    department: "Operations",
    designation: "Operations Executive",
    joiningDate: "2023-04-10",
    baseSalary: 52000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 1,
    lateDays: 1,
    halfDays: 1,
    overtimeHours: 2,
    attendancePercentage: 92.3,
    performanceScore: 80,
    customerSatisfaction: 4.1,
    managerRating: 4,
    feedback: "Handles document verification pipelines smoothly. Helpful and coordinates with IT when needed.",
    orgHierarchy: { manager: "Sunita Rao", role: "Executive" },
    leaveBalance: { casual: 2, sick: 3, paid: 7, unpaid: 1 },
    bonus: 1000
  },
  {
    id: "OASIS-018",
    name: "Neha Gupta",
    email: "neha.gupta@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1589156280159-27698a70f29e?w=150",
    department: "Finance",
    designation: "Finance Manager",
    joiningDate: "2020-09-01",
    baseSalary: 130000,
    payrollStatus: "Paid",
    presentDays: 25,
    absentDays: 1,
    lateDays: 2,
    halfDays: 0,
    overtimeHours: 0,
    attendancePercentage: 96.2,
    performanceScore: 92,
    customerSatisfaction: 4.6,
    managerRating: 5,
    feedback: "Meticulous work on monthly balance sheet reporting and payroll reconciliation cycles.",
    orgHierarchy: { manager: "Vikram Malhotra", role: "Manager" },
    leaveBalance: { casual: 5, sick: 8, paid: 16, unpaid: 0 },
    bonus: 5000
  },
  {
    id: "OASIS-019",
    name: "Harish Verma",
    email: "harish.verma@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150",
    department: "Claims",
    designation: "Senior Claims Executive",
    joiningDate: "2021-02-14",
    baseSalary: 85000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 1,
    lateDays: 3, // 1 half day
    halfDays: 1,
    overtimeHours: 4,
    attendancePercentage: 92.3,
    performanceScore: 86,
    customerSatisfaction: 4.5,
    managerRating: 4,
    feedback: "Reliable and precise execution of claim validation routines. Consistently meets timelines.",
    orgHierarchy: { manager: "Deepika Padukone", role: "Senior Executive" },
    leaveBalance: { casual: 3, sick: 6, paid: 11, unpaid: 1 },
    bonus: 3000
  },
  {
    id: "OASIS-020",
    name: "Manish Malhotra",
    email: "manish.malhotra@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150",
    department: "IT",
    designation: "IT Security Analyst",
    joiningDate: "2022-04-18",
    baseSalary: 105000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 2,
    lateDays: 0,
    halfDays: 0,
    overtimeHours: 4,
    attendancePercentage: 92.3,
    performanceScore: 88,
    customerSatisfaction: 4.6,
    managerRating: 4,
    feedback: "Conducted exhaustive cybersecurity training and keeps system firewalls and VPNs optimized.",
    orgHierarchy: { manager: "Amit Sharma", role: "Security Analyst" },
    leaveBalance: { casual: 4, sick: 4, paid: 10, unpaid: 2 },
    bonus: 4000
  },
  {
    id: "OASIS-021",
    name: "Abhinav Bindra",
    email: "abhinav.bindra@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80",
    department: "Sales",
    designation: "Sales Associate",
    joiningDate: "2023-07-10",
    baseSalary: 48000,
    payrollStatus: "Paid",
    presentDays: 25,
    absentDays: 1,
    lateDays: 1,
    halfDays: 0,
    overtimeHours: 6,
    attendancePercentage: 96.2,
    performanceScore: 87,
    salesGenerated: 750000,
    targetAchievement: 100,
    policiesSold: 12,
    customerSatisfaction: 4.5,
    managerRating: 4,
    feedback: "Strong month for Abhinav. Achieved his sales quota and maintained excellent CRM logs.",
    orgHierarchy: { manager: "Rajesh Kumar", role: "Associate" },
    leaveBalance: { casual: 3, sick: 4, paid: 8, unpaid: 1 },
    bonus: 2000
  },
  {
    id: "OASIS-022",
    name: "Saina Nehwal",
    email: "saina.nehwal@oasisinsurance.in",
    avatar: "https://images.unsplash.com/photo-1594744803329-e58b31de215f?w=150",
    department: "Operations",
    designation: "Operations Coordinator",
    joiningDate: "2023-08-15",
    baseSalary: 50000,
    payrollStatus: "Paid",
    presentDays: 24,
    absentDays: 1,
    lateDays: 3, // 1 half day
    halfDays: 1,
    overtimeHours: 0,
    attendancePercentage: 92.3,
    performanceScore: 82,
    customerSatisfaction: 4.3,
    managerRating: 4,
    feedback: "Effectively supports shift schedules and vendor alignment. Enthusiastic team member.",
    orgHierarchy: { manager: "Rahul Dravid", role: "Coordinator" },
    leaveBalance: { casual: 4, sick: 3, paid: 9, unpaid: 1 },
    bonus: 1000
  }
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "LR-101",
    employeeId: "OASIS-009",
    employeeName: "Rohit Sharma",
    department: "Sales",
    leaveType: "Casual",
    startDate: "2026-07-20",
    endDate: "2026-07-21",
    days: 2,
    status: "Pending",
    reason: "Personal family event in Mumbai."
  },
  {
    id: "LR-102",
    employeeId: "OASIS-006",
    employeeName: "Sneha Reddy",
    department: "Claims",
    leaveType: "Sick",
    startDate: "2026-07-16",
    endDate: "2026-07-17",
    days: 2,
    status: "Pending",
    reason: "Dental procedure recovery."
  },
  {
    id: "LR-103",
    employeeId: "OASIS-012",
    employeeName: "Ananya Pandey",
    department: "HR",
    leaveType: "Paid",
    startDate: "2026-07-27",
    endDate: "2026-07-30",
    days: 4,
    status: "Approved",
    reason: "Annual vacation with family."
  },
  {
    id: "LR-104",
    employeeId: "OASIS-015",
    employeeName: "Tanvi Shah",
    department: "IT",
    leaveType: "Casual",
    startDate: "2026-07-24",
    endDate: "2026-07-24",
    days: 1,
    status: "Pending",
    reason: "Routine health checkup."
  }
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: "ACT-001",
    user: "Vikram Malhotra",
    role: "Super Admin",
    action: "Updated global PF contribution rule from 12% to 12.5%",
    timestamp: "2026-07-14T11:20:00Z"
  },
  {
    id: "ACT-002",
    user: "Priya Patel",
    role: "HR",
    action: "Uploaded biometric check-in spreadsheet (45 records matched)",
    timestamp: "2026-07-14T10:45:00Z"
  },
  {
    id: "ACT-003",
    user: "Sanjay Mehta",
    role: "Dept Head",
    action: "Approved Sales team Q2 performance incentive brackets",
    timestamp: "2026-07-14T09:15:00Z"
  },
  {
    id: "ACT-004",
    user: "Priya Patel",
    role: "HR",
    action: "Approved Leave Request LR-103 for Ananya Pandey",
    timestamp: "2026-07-14T08:30:00Z"
  }
];
